remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

logo: Pic.JPG

title: Varona, Adrian Mark B.
description: I’m a Computer Science student


show_downloads: false

<a href="page2.html" class="next-page">Next Page →</a>

<style>
.next-page {
  color: #267CB9;
  text-decoration: none;
  font-weight: bold;
}
.next-page:hover {
  text-decoration: underline;
}
</style>
