remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

logo: Pic.JPG

title: Varona, Adrian Mark B.
description: Iâ€™m a Computer Science student


show_downloads: false

.next-btn {
  display: inline-block;
  padding: 10px 20px;
  background: #007acc;
  color: white;
  text-decoration: none;
  border-radius: 5px;
  font-weight: bold;
}
.next-btn:hover {
  background: #005fa3;
}
