remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

logo: Pic.JPG

title: Varona, Adrian Mark B.
description: Iâ€™m a Computer Science student


show_downloads: false

# Optional navigation links
nav:
  - name: Home
    link: /
  - name: education
    link: /education/


