remote_theme: pages-themes/midnight@v0.2.0
plugins:

tagline: [To innovate and improthe world]
description: [I’m a Computer Science student with a passion for solving problems through technology. I enjoy learning about software development, algorithms, and emerging technologies like AI and data science. I’m always looking for opportunities to apply my skills through projects and collaborations.]
